config/routes.rb
Rails.application.routes.draw do


  get '/', to: 'sessions#welcome', as: 'home'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  delete 'logout', to: 'sessions#destroy'


  
  resources :users do 
  resources :entries
  end 
  
  resources :entries do
    resources :topics
  end

  resources :topics

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/MathFunctions.rb
class MathFunctions

    def merge_sorted(arr1, arr2)
        result = []
        i = 0
        j = 0
        while arr1.length !=0 && arr2.length !=0 do 
            if arr1[0]<=arr2[0] 
                result.push(arr1.shift())
            else 
                result.push(arr2.shift())
            end
        end
        return result.concat(arr1).concat(arr2)
    end

    def merge_sort(arr) 
        return arr if arr.length<=1 
        mid = (arr.length/2).floor()
        left = merge_sort(arr.slice(0, mid))
        right = merge_sort(arr.slice(mid, (arr.length - mid)))
        return merge_sorted(left, right)

    end
    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :entry
end

app/models/user.rb
class User < ApplicationRecord
    has_many :entries
    has_many :topics, through: :entries

    validates :name, presence: true
    validates :email, uniqueness: true, presence: true
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?, :user_ok? 


    def current_user    
        @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !current_user.nil?  
    end

     def user_ok?(user)
        if !!user == false || (user.id != current_user.id)  
            redirect_to '/'
        else
            true
       end
     end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    # before_action :require_login
 
     def index
         @user = User.find_by_id(session[:user_id])
         if @user 
             @entries = @user.entries
             redirect_to entries_path(@entries)
         else 
             byebug
            # raise "Line 9 in Entry".inspect
         end
 
     end
 
     def new
         @entry = Entry.new
     end
 
     def create
         @user = current_user if logged_in?
         if @user
             @entry = @user.entries.build(entry_params)
             if @entry.save 
                 #raise.params.inspect
               #   byebug
                 redirect_to entry_path(@entry)
             else 
                 @errors = @entry.errors
                 render :'entries/new'
             end
         end
     end
 
     def show
        @entry = Entry.find_by_id(params[:id])
     end

     def edit
        if logged_in?
            @user = current_user
            user_ok?(@user)
            @entry = Entry.find_by_id(params[:id])
            redirect_to '/' if @user.id != @entry.user_id
        else
            redirect_to '/'
        end
    end

     def update
        raise.params.inspect
     end

     def destroy
        raise.params.inspect
     end

     private
 
     def require_login
         return head(:forbidden) unless session.include? :user_id
     end
 
     private
 
 def entry_params
     params.require(:entry).permit(:title, :post, :user_id, :custdate)
 end
 
 end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
    end

    def new
    end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            flash[:error] = "Login unsucessful."
            redirect_to login_path
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

    def new
        @topic = Topic.new
        @entry = Entry.find_by_id(params[:entry_id])
    end

    def create
        raise.params.inspect
        @user = current_user if logged_in?
        @entry = Entry.find_by_id(params[:entry_id])
    end




    private 

    def topic_params
        params.require(:topic).permit(:keyword, :entry_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]

    def new
        @user = User.new
    end

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            # raise.params.inspect
            redirect_to user_path(@user)
        else 
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

   

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/edit.html.erb
<h1>Edit</h1>
<h3>User: <%= @user.name %></h3>
<h4>Title: <%= @entry.title %></h4>
<h5>Date: <%= @entry.custdate %></h5>


<%= form_for [@user, @entry] do |f| %>
<%= f.label :Change_to_Custom_Date_if_not_for_today%><br><br>
<%= f.date_select :custdate %><br><br>
<%= f.label :title %>
<%= f.text_field :title%><br><br>
<%= f.label :post %><br>
<%= f.text_area :post, class: "post" %>

<%= f.submit "Save Edited" %>
<% end %>

<div class = "outputArea">
<div id = "titleSpace"><b></b>
<br><br></div>

<div id = "postSpace">
</div>
</div>

app/views/entries/index.html.erb
<h1>Entries Index</h1>
<p> <%= @entries.last %></p>

app/views/entries/new.html.erb
<h1>User: <%= current_user.name %> </h1>
<h2>New Entry Page</h2>



<%= form_for [@user, @entry] do |f| %>
<%= f.label :Change_to_Custom_Date_if_not_for_today%><br><br>
<%= f.date_select :custdate %><br><br>
<%= f.label :title %>
<%= f.text_field :title%><br>
<%= f.label :post %><br>
<%= f.text_area :post, class: "post" %>

<%= f.submit "Save" %>
<% end %>

<div class = "outputArea">
<div id = "titleSpace"><b></b>
<br><br></div>

<div id = "postSpace">
</div>
</div>


<%# <script>
let titleArea = document.querySelector("#titleSpace > b")

let getTitle = document.querySelector("#entry_title")
getTitle.addEventListener("keydown", function(e) {
  //  if (getTitle.value.length > 5) debugger
    if (e.keyCode==8) {
        titleArea.innerText = titleArea.innerText.slice(0, -1)
    }
    titleArea.innerText = e.target.value
})

let postArea = document.querySelector("#entry_post")

let postOutput = document.querySelector("#postSpace")
postArea.addEventListener("keydown", function(e) {
    console.log(e.keyCode)
    if (e.code=="Enter") { 
        e.preventDefault()
        postOutput.innerHTML += `<br>`
        } else if (e.keyCode==8) {
            console.log("back")
           postOutput.innerText = postOutput.innerText.slice(0, -1)
        } else if (e.keyCode==32) {
            console.log("space")
            postOutput.innerText += ' '
        } else 
        {
            console.log("normal")
            postOutput.innerText += e.target.value.slice(-1)
        }
})


</script> %>

app/views/entries/show.html.erb
<h1>You're latest entry, <%= @entry.user.name %></h1>

<p><b> Title: <i><%= @entry.title %> </i></b></p>
<p> <%= @entry.custdate.strftime("%A %B %d, %Y") %> </p>
<p> Text:<%= simple_format(@entry.post) %> </p>

<%= link_to "Add Indexes", new_entry_topic_path(@entry) %>

<%= link_to "Edit Entry", edit_user_entry_path(@entry.user, @entry)%>

<%= link_to "Delete Entry", entry_path(@entry), method: :delete, data: {confirm: "Are you sure you want to delete this Entry?"} %>